version: "3.1"

services:
  postgres-db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: public
    ports:
      - 5432:5432
    mem_limit: 1g
    cpus: 1
