version: "3.1"

services:
  api-solid:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_solid
    ports:
      - 5432:5432
